name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    #   GCAL_API_KEY: ${{ secrets.GCAL_API_KEY }}
    #   GCAL_CLIENT_ID: ${{ secrets.GCAL_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
